// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaX5_4FTRAaGAU9CDNmjIM2mPTwGnvSdI',
    appId: '1:163710806322:web:0a617b736bea979d70cf2b',
    messagingSenderId: '163710806322',
    projectId: 'recipe-app-325d3',
    authDomain: 'recipe-app-325d3.firebaseapp.com',
    storageBucket: 'recipe-app-325d3.firebasestorage.app',
    measurementId: 'G-FMNYRG9Q4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMN2Et7fX7I8GEvIXXWJUXbNGv9Cqj3ZA',
    appId: '1:163710806322:android:3e0bb9587b30598e70cf2b',
    messagingSenderId: '163710806322',
    projectId: 'recipe-app-325d3',
    storageBucket: 'recipe-app-325d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ULzdvnsiaF0GiTPknbqzR1KWkcNp17Q',
    appId: '1:163710806322:ios:f3883387f65abe4670cf2b',
    messagingSenderId: '163710806322',
    projectId: 'recipe-app-325d3',
    storageBucket: 'recipe-app-325d3.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ULzdvnsiaF0GiTPknbqzR1KWkcNp17Q',
    appId: '1:163710806322:ios:f3883387f65abe4670cf2b',
    messagingSenderId: '163710806322',
    projectId: 'recipe-app-325d3',
    storageBucket: 'recipe-app-325d3.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaX5_4FTRAaGAU9CDNmjIM2mPTwGnvSdI',
    appId: '1:163710806322:web:4968c2d64a1baed470cf2b',
    messagingSenderId: '163710806322',
    projectId: 'recipe-app-325d3',
    authDomain: 'recipe-app-325d3.firebaseapp.com',
    storageBucket: 'recipe-app-325d3.firebasestorage.app',
    measurementId: 'G-SPYLWBBY97',
  );

}